- name: Proxmox stuff
  hosts: 10.10.0.30
  vars:
    name: ubuntu
  become: true
  tasks:
    - name: Install pip3
      ansible.builtin.package:
        name: python-pip
        state: present
    - name: Install proxmoxer
      ansible.builtin.pip:
        name: proxmoxer
        state: present
    - name: Set VM Name
      set_fact:
        yeppers: "ubuntu-{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"

    - name: Clone VM
      proxmox_kvm:
        api_user: root@pam
        api_password: 9925408
        api_host: 10.10.0.10
        clone: UbuntuTemplate   # The VM source
        name: "{{ yeppers }}"  # The target VM name
        node: NODE3
        storage: local-lvm
        format: qcow2
        timeout: 500  # Note: The task can take a while. Adapt

    - name: Start VM
      proxmox_kvm:
        api_user: root@pam
        api_password: 9925408
        api_host: 10.10.0.10
        name: "{{ yeppers }}"
        node: NODE3
        state: started

    - name: Get VM ID
      shell: qm list | grep "{{ yeppers }}" | awk '{ print $1 }'
      register: thevmid

    - name: Debug VM ID
      debug:
        var: thevmid.stdout

    - name: Get Network Configuration
      shell: qm config "{{ thevmid.stdout }}" | grep ^net0 | awk -F, '{print $1}' | awk -F= '{print $2}'
      register: stuff

    - name: Debug Network Configuration
      debug:
        var: stuff.stdout

    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:
        minutes: 5

    - name: Get ARP
      shell: nmap -sT 10.10.0.0/16
      register: nmap

    - name: Debug ARP
      debug:
        var: nmap 

    - name: Get IP Address
      shell: arp | grep "{{ stuff.stdout|lower | regex_replace('^\\/|\\/$', '') }}" | awk '{ print $1 }'
      register: theip

    - name: Debug IP Address
      debug:
        var: theip

    - name: Slack Notification
      community.general.slack:
        token: zQzYzg1NWYzYTIxMjMzZTI2YzljZmRhZDJkYzZjMWFhNTMyZjE3MGYwMQ8a2254b648b25a9e355f508ab2ef5fcb
        msg: |
          ### Your Server is READY!! ###
          --------------------------------------
          'Server': "{{ yeppers }}"
          'IP ADDRESS': "{{ theip.stdout }}"
          'URL': ssh://networkchuck@{{ theip.stdout }}
          --------------------------------------
        channel: '#ansible'
        color: good
        username: 'Ansible on {{ inventory_hostname }}'
        link_names: 0
        parse: 'none'
      ignore_errors: true
