---
- name: Proxmox LXC stuff
  hosts: 10.10.0.30
  vars:
    name: ubuntu
  become: true
  tasks:
    - name: Install pip3
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install proxmoxer
      ansible.builtin.apt:
        name: python3-proxmoxer
        state: present

    - name: Set LXC Container Name
      set_fact:
        yeppers: "ubuntu-{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"

    - name: Create LXC Container
      community.general.proxmox:
        api_host: 10.10.0.30  # Replace with your Proxmox host IP
        api_user: root@pam
        api_password: 9925408
        hostname: NODE3
        node: NODE3
        vmid: "{{ yeppers | int }}"
        state: present
        ostemplate: local:ubuntu-23.04-standard_23.04-1_amd64.tar.zst
        storage: local-lvm
        password: root_password_for_container
        onboot: true
        netif: name=eth0,bridge=vmbr0,ip=dhcp

    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:
        minutes: 5

    - name: Get LXC Container IP Address
      community.general.proxmox:
        api_host: 10.10.0.30
        api_user: root@pam
        api_password: 9925408
        node: NODE3
        vmid: "{{ yeppers | int }}"
        command: query
      register: lxc_info

    - name: Debug LXC Container IP Address
      debug:
        var: lxc_info.network.eth0.ip

    - name: Slack Notification
      community.general.slack:
        token: zQzYzg1NWYzYTIxMjMzZTI2YzljZmRhZDJkYzZjMWFhNTMyZjE3MGYwMQ8a2254b648b25a9e355f508ab2ef5fcb
        msg: |
          ### Your LXC Container is READY!! ###
          --------------------------------------
          'Container': "{{ yeppers }}"
          'IP ADDRESS': "{{ lxc_info.network.eth0.ip }}"
          'URL': ssh://networkchuck@{{ lxc_info.network.eth0.ip }}
          --------------------------------------
        channel: '#ansible'
        color: good
        username: 'Ansible on {{ inventory_hostname }}'
        link_names: 0
        parse: 'none'
      ignore_errors: true
