- name: Proxmox LXC Cloning
  hosts: 10.10.0.30
  vars:
    container_name: ubuntu
  tasks:
    - name: Install community.general collection
      ansible.builtin.command: ansible-galaxy collection install community.general

    - set_fact:
        yeppers: "ubuntu-{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
    
    - proxmox_lxc:
        api_user: root@pam
        api_password: 9925408
        api_host: 10.10.0.30
        clone: UbuntuTemplate  # The LXC source
        name: "{{ yeppers }}"  # The target LXC container name
        node: NODE3
        storage: local-lvm
        timeout: 500  # Note: The task can take a while. Adapt
    
    - name: start LXC container
      proxmox_lxc:
        api_user: root@pam
        api_password: PASSWORD
        api_host: 10.10.0.30
        name: "{{ yeppers }}"
        node: NODE3
        state: started
    
    - name: get LXC container ID
      shell: pct list | grep "{{ yeppers }}" | awk '{ print $1 }'
      register: thelxcid
    
    - name: debug LXC container ID
      debug:
        var: thelxcid.stdout 
    
    - name: Pause for 1 minute to build app cache
      ansible.builtin.pause:
        minutes: 1
    
    - name: get LXC container IP
      shell: pct exec "{{ thelxcid.stdout }}" -- ip a show dev eth0 | grep -oP 'inet \K\S+'
      register: theip
    
    - name: debug LXC container IP
      debug:
        var: theip.stdout
    
    - name: Slack Notification
      community.general.slack:
        token: zQzYzg1NWYzYTIxMjMzZTI2YzljZmRhZDJkYzZjMWFhNTMyZjE3MGYwMQ8a2254b648b25a9e355f508ab2ef5fcb
        msg: |
          ### Your LXC Container is READY!! ###
          --------------------------------------
          `Container`: "{{ yeppers }}"
          `IP ADDRESS`: "{{ theip.stdout }}"
          'URL': ssh://user@{{ theip.stdout }}
          --------------------------------------
        channel: '#ansible'
        color: good
        username: 'Ansible on {{ inventory_hostname }}'
        link_names: 0
        parse: 'none'
      ignore_errors: true
